### ISSUE TITLE
Image export doesn't account for line width

### ISSUE THREAD

**Issue by ahmad24** [literallycanvas/literallycanvas#442] opened 2016-11-15 19:21 UTC
If you select the line tool and you draw an arrow with max stroke width then try to export an image it will be cropped, it doesn't consider the arrow head as part of the arrow boundaries.

**getBoundingRect** Line method should modify.

Current code:
```
defineShape('Line', {
  constructor: function(args) {
    if (args == null) {
      args = {};
    }
    this.x1 = args.x1 || 0;
    this.y1 = args.y1 || 0;
    this.x2 = args.x2 || 0;
    this.y2 = args.y2 || 0;
    this.strokeWidth = args.strokeWidth || 1;
    this.strokeStyle = args.strokeStyle || null;
    this.color = args.color || 'black';
    this.capStyle = args.capStyle || 'round';
    this.endCapShapes = args.endCapShapes || [null, null];
    return this.dash = args.dash || null;
  },
  draw: function(ctx) {
    ctx.lineWidth = this.strokeWidth;
    ctx.strokeStyle = this.color;
    ctx.lineCap = this.capStyle;
    if (this.dash) {
      ctx.setLineDash(this.dash);
    }
    ctx.beginPath();
    ctx.moveTo(this.x1, this.y1);
    ctx.lineTo(this.x2, this.y2);
    ctx.stroke();
    if (this.dash) {
      ctx.setLineDash([]);
    }
    if (this.endCapShapes[0]) {
      lineEndCapShapes[this.endCapShapes[0]](ctx, this.x1, this.y1, Math.atan2(this.y1 - this.y2, this.x1 - this.x2), {
        color: this.color
      });
    }
    if (this.endCapShapes[1]) {
      return lineEndCapShapes[this.endCapShapes[1]](ctx, this.x2, this.y2, Math.atan2(this.y2 - this.y1, this.x2 - this.x1), {
        color: this.color
      });
    }
  },
  getBoundingRect: function () {
    return {
      x: Math.min(this.x1, this.x2) - this.strokeWidth  / 2,
      y: Math.min(this.y1, this.y2) - this.strokeWidth  / 2,
      width: Math.abs(this.x2 - this.x1) + this.strokeWidth  / 2,
      height: Math.abs(this.y2 - this.y1) + this.strokeWidth  / 2
    };
  },
  toJSON: function() {
    return {
      x1: this.x1,
      y1: this.y1,
      x2: this.x2,
      y2: this.y2,
      strokeWidth: this.strokeWidth,
      color: this.color,
      capStyle: this.capStyle,
      dash: this.dash,
      endCapShapes: this.endCapShapes
    };
  },
  fromJSON: function(data) {
    return createShape('Line', data);
  }
}); 
```

It should be updated to something like this:

```
defineShape('Line', {
  constructor: function(args) {
    if (args == null) {
      args = {};
    }
    this.x1 = args.x1 || 0;
    this.y1 = args.y1 || 0;
    this.x2 = args.x2 || 0;
    this.y2 = args.y2 || 0;
    this.strokeWidth = args.strokeWidth || 1;
    this.strokeStyle = args.strokeStyle || null;
    this.color = args.color || 'black';
    this.capStyle = args.capStyle || 'round';
    this.endCapShapes = args.endCapShapes || [null, null];
    return this.dash = args.dash || null;
  },
  draw: function(ctx) {
    ctx.lineWidth = this.strokeWidth;
    ctx.strokeStyle = this.color;
    ctx.lineCap = this.capStyle;
    if (this.dash) {
      ctx.setLineDash(this.dash);
    }
    ctx.beginPath();
    ctx.moveTo(this.x1, this.y1);
    ctx.lineTo(this.x2, this.y2);
    ctx.stroke();
    if (this.dash) {
      ctx.setLineDash([]);
    }
    if (this.endCapShapes[0]) {
      lineEndCapShapes[this.endCapShapes[0]](ctx, this.x1, this.y1, Math.atan2(this.y1 - this.y2, this.x1 - this.x2), {
        color: this.color
      });
    }
    if (this.endCapShapes[1]) {
      return lineEndCapShapes[this.endCapShapes[1]](ctx, this.x2, this.y2, Math.atan2(this.y2 - this.y1, this.x2 - this.x1), {
        color: this.color
      });
    }
  },
  getBoundingRect: function () {
    return {
      x: Math.min(this.x1, this.x2) - this.strokeWidth * 2,
      y: Math.min(this.y1, this.y2) - this.strokeWidth * 2,
      width: Math.abs(this.x2 - this.x1) + this.strokeWidth * 4,
      height: Math.abs(this.y2 - this.y1) + this.strokeWidth * 4,
    };
  },
  toJSON: function() {
    return {
      x1: this.x1,
      y1: this.y1,
      x2: this.x2,
      y2: this.y2,
      strokeWidth: this.strokeWidth,
      color: this.color,
      capStyle: this.capStyle,
      dash: this.dash,
      endCapShapes: this.endCapShapes
    };
  },
  fromJSON: function(data) {
    return createShape('Line', data);
  }
});
```

**Comment by irskep** [comment] 2018-01-08 23:43
Your description and fix makes sense, but I will wait for an actual pull request instead of a code dump to fix it in a release.

**Comment by irskep** [comment] 2018-01-09 00:26
Duplicate of #363, actually

**Closed by irskep** 2018-01-09 00:26 UTC
Labels: bug
