### ISSUE TITLE
Allow shapes to be rotated programmatically

### ISSUE THREAD

**Issue by mkvalentine** [literallycanvas/literallycanvas#276] opened 2015-04-23 19:27 UTC
Hi there,

I’m in a Computer Graphics project class at Yale, and my team is making a virtual “paper napkin” where people can pass a drawing back & forth to generate ideas and random art projects. We want to transform the shapes on the canvas in between passes to help build new ideas and unintended images. Ideally we’d like to zoom, pan and rotate in between passes. So far, we have zoom and pan working well, but we can’t figure out how to rotate the image. We want to pass the json shapes rather than an image file, and once the shapes are rotated the new user should be able to draw on a normal, horizontal canvas.

Do you have any idea how to implement such a rotation function?

Thanks,
Megan

*****
Megan Valentine
Yale University 2016 | Computing & the Arts
megan.valentine@yale.edu

**Comment by irskep** [comment] 2015-04-23 19:35
Are you using Literally Canvas or are you just asking about the canvas API in general?

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations

**Comment by mkvalentine** [comment] 2015-04-23 21:06
We’re using literally canvas. Is it possible to use the general canvas API functions on the literally canvas object?

**Comment by irskep** [comment] 2015-04-23 21:55
Ah, I see. Sorry for misunderstanding.

The challenge is more that Literally Canvas's user interface (and consequently, tool API) would have to change to allow rotations. It should be simple to add rotation as a shape feature, but there isn't a good way to perform the rotation in the UI.

If you didn't need a UI for rotation, then you could add the rotation feature to the shapes and rotate programmatically, which I would be happy to provide guidance for.

**Comment by mkvalentine** [comment] 2015-04-23 23:27
Adding the rotation feature to the shapes to rotate programmatically would work very well for our project. Some guidance as to which functions we should be changing in literallycanvas.js would be great! Thanks for being willing to help us!

-Megan

**Comment by irskep** [comment] 2015-04-23 23:35
Here's the file you'll want to edit:

https://github.com/literallycanvas/literallycanvas/blob/master/src/core/shapes.coffee

For each shape you want to rotate:

1. Add an 'angle' option to the constructor
2. Update the `toJSON()` method of the shape to include the option, so it doesn't get lost between loads
3. Modify the `draw()` method to use the canvas rotation transform. Remember to use `ctx.save()` and `ctx.restore()` at the beginning and end of the method to avoid leaving the rotation in place.

In your `draw()` implementations, please only apply the transform (and save/restore) if the angle is nonzero. Transforms have performance implications that I would like to avoid for most uses.

If you tell me more about specifically when and how you want to apply the rotation, I can give you some ideas about where to make the rest of your changes. It's not clear to me if you want to do it to an active drawing, or during setup before drawing begins.

**Comment by irskep** [comment] 2015-04-23 23:37
Also, if you're trying to rotate the entire drawing, that might be more of a challenge, though a manageable one. You'd still need the rotation feature, but you'd also need to translate everything, since rotation would just move the shape in place.

**Comment by mkvalentine** [comment] 2015-04-23 23:56
We want to do rotations during setup on the passed image before the new player’s drawing session begins, and it might be okay to just rotate individual shapes because the goal is really to just change the picture’s perspective in some way. This is so helpful! Thank you!

**Comment by irskep** [comment] 2015-04-24 00:06
You're welcome!

While the documentation claims that snapshots should be treated as black boxes, in your case it seems most expedient to just parse the JSON, modify the `angle` values, and `LC.loadSnapshot()` the result. It might not work forever, but certainly will for the next couple of years. :-)

**Comment by irskep** [comment] 2016-06-08 22:20
Now duplicate of #365.

**Closed by irskep** 2016-06-08 22:20 UTC
