### ISSUE TITLE
Problem loading editor in AngularJS-Bootstrap app

### ISSUE THREAD

**Issue by robertovivian** [literallycanvas/literallycanvas#279] opened 2015-05-28 16:29 UTC
I’m trying to use Literally Canvas in an HTML5 angularjs-bootstrap app. 
I want to load the editor with an image in a modal window: the editor is loaded but it seems frozen and the image isn’t shown. 
If I resize the window (or press alt+F) the contents appear, the image is visualized and all the functions are available. Where is the problem?  I’m using Firefox 38.0.1.

Fragme of index.html: 
```
 	<div class="container-fluid">
		<div class="row">
			<div  style="padding: 10px" ng-controller='LiterallyCanvasCtrl'>
				<button class='btn btn-primary' ng-click="openModal()" >
					Open modal
				</button>
			</div>
		</div>
	</div>
```
Modal window code: 
```
 <div class="modal-header">
    <button type="button" class="close" ng-click="close(false)" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" ng-model="modalHeader">{{modalHeader}}</h4>
</div>
<div class="modal-body">
	<div>
		<div style="padding: 10px" class="col-md-12">
			<div class="col-md-12" style="padding: 10px">
				<div class="literally" ng-init="initLC()")></div>
				<!-- script>
				 LC.init(
					document.getElementsByClassName('literally')[0],
					{imageURLPrefix: '../img'}
				);
				</script-->
			</div>
		</div>
	</div>
</div>
<div class="modal-footer">
	<div class="col-md-1">
	    	<button type="button" ng-click="close()" class="btn btn-primary" data-dismiss="modal">Close</button>
    </div>
</div>
```
AngularJS code: 

```
var pageModule = angular.module('pageModule', ['ui.bootstrap']);

pageModule.controller('LiterallyCanvasCtrl', function($scope, $log, $modal) {
	$scope.lc = null;
	var editModal = null
	
	$scope.openModal = function() {
		$log.info('LiterallyCanvasCtrl: open modal window');
		// Open modal window
		editModal = $modal.open({
			templateUrl: 'html/modal-window.html',
			controller: 'ModalInstanceCtrl',
			size:'lg',
			backdrop:'static',
			resolve: {
			}
		});

		editModal.opened.then(function(){});
	};

});

pageModule.controller('ModalInstanceCtrl', function($scope, $modalInstance, $log) {
	$scope.modalHeader = "Modal image edit";
	$scope.lc == null;

	$scope.initLC = function(){
		// Init editor
		if ($scope.lc == null) {
			$scope.lc = LC.init(
					document.getElementsByClassName('literally')[0],
					{imageURLPrefix: 'img'}
			);
		}
		// set image as part of the drawing
		var newImage = new Image();
		newImage.src = "html/sample.JPG";
		$scope.lc.saveShape(LC.createShape('Image', {x: 0, y: 0, image: newImage}));
	};

	$scope.close = function() {
		$modalInstance.dismiss('cancel');
	};

});
```

**Comment by irskep** [comment] 2015-05-28 17:56
What version are you on? I released 0.4.2 a few days ago, which might have a bug fix for this.

**Comment by irskep** [comment] 2015-05-28 17:57
Also, what does your app do? I'm always interested to know what people are doing with this library.

**Comment by robertovivian** [comment] 2015-06-03 07:37
Hi irskep, 
I'm using version 0.4.2. 
If you want I can send you a simple zip with an example of the issue.

**Comment by irskep** [comment] 2015-06-03 15:30
That would be great.

**Comment by robertovivian** [comment] 2015-06-03 15:56
Here a  [link] (http://1drv.ms/1KMLvsd) to download a zip with the sample. 
Thank you for your interest.

**Comment by irskep** [comment] 2015-06-09 01:37
(I haven't forgotten about this, I've just been busy)

**Comment by robertovivian** [comment] 2015-06-09 07:16
Ok, thanks for your feedback. 
To answer your previous post, I'm developing a pilot app that capture a video frame and make some simple editing to captured image. 
I’d like to use your widget if it works fine. For now there is no business behind this pilot.

**Comment by irskep** [comment] 2015-06-27 19:33
I finally got around to trying this. It looks like it works if you open
the modal and then resize the page. I don't know why yet.

**Comment by irskep** [comment] 2015-06-27 19:42
The problem is that when Literally Canvas is initialized, its container
has no size. You need to make sure the container element is in the DOM
before you add Literally Canvas to it, because it needs the size info to
configure its internal DOM nodes.

I know this is not ideal, but that's the way it is for this version.
Please let me know if this doesn't fix the problem, but I'm pretty sure
that's what needs to happen.

**Closed** 2015-06-27 19:42 UTC

**Comment by robertovivian** [comment] 2015-06-29 15:04
AngularJS is a little bit complicated in initialization of objects and there is not much control on it. 
Have you been able to make my sample code work?

**Comment by irskep** [comment] 2015-06-29 17:16
No, that's up to you.

**Comment by endra89** [comment] 2016-01-07 03:34
@robertovivian  any problem solve? same problem with me on bootstrap pill/tab css conflict

**Comment by raident30** [comment] 2016-08-16 09:06
Hello! I have a solution for this..

After the modal is shown with jquery, initialize literallycanvas and itshould work.
` $('#my-modal').modal();`

```
$('#my-modal').on('shown.bs.modal', function () {
     lc = LC.init(
    document.getElementsByClassName('lc')[0],
    {
    });
});
```
i hope this helps
