### ISSUE TITLE
New Polygon tool not working - IE11

### ISSUE THREAD

**Issue by maxsdw** [literallycanvas/literallycanvas#308] opened 2015-08-20 13:16 UTC
The new Polygon tool is not properly working on IE11, the line always starts from top-left corner and it is imposible to complete the shape.

**Comment by irskep** [comment] 2015-08-21 03:39
Fixed in master. The cause was quite silly: I introduce some new events `pointerup`, `pointerdown`, `pointermove`, and `pointerdrag`, forgetting that there's a whole new "standard" for "pointer" events that only Internet Explorer implements. The effect was that the polygon tool was getting two copies of every event: one on purpose, one by accident.

Here's some fixed JavaScript in case this a pressing problem for you: https://gist.githubusercontent.com/irskep/24ea6793131273ea875d/raw/da78f00d067894993ca5b8bfea9156982b867a90/gistfile1.txt

**Closed by irskep** 2015-08-21 03:39 UTC
Labels: bug

**Comment by irskep** [comment] 2015-08-21 03:40
And thanks for the bug report, by the way. This was pretty bad.

**Comment by maxsdw** [comment] 2015-08-21 03:56
Perfect, thanks to you!.

**Comment by irskep** [comment] 2015-08-21 03:57
I just released v0.4.8 since this is pretty critical, so you can just get the release the normal way.
