### ISSUE TITLE
Whiteboard collaberation with TogetherJS

### ISSUE THREAD

**Issue by anik786** [literallycanvas/literallycanvas#387] opened 2016-03-02 16:58 UTC
Would it be possible to add [TogetherJS](https://togetherjs.com/) support to allow multi user collaberation including audio chat!

TogetherJs is a free framework that allows multiple users to collaborate and is developed by Mozilla, meaning that it will probably be well supported in the future.

Furthermore, everything is client side, meaning you don't need to do any backend coding.

It's also used in [JSFiddle](https://jsfiddle.net/)!

There is also a fair tutorial in how to use TogetherJs for a drawing application: https://hacks.mozilla.org/2013/10/introducing-togetherjs/
with a full example here:
https://togetherjs.com/examples/drawing/
http://jsfiddle.net/5f8FL/1/

which would hopefully help!

**Comment by irskep** [comment] 2016-03-02 17:39
Mozilla has a history of abandoning things that are not their core competency. (Firefox OS, Persona, Thunderbird being the most recent examples.) I'd much rather have this be a plugin than part of the core library. The real challenge is fixing the API to support this kind of thing more easily.

**Comment by anik786** [comment] 2016-03-03 02:45
I think that improving the plugin API part is perhaps the most important thing, because I would imagine that many users want a drawing plugin that is collaborative. 

Therefore I believe it's important to improve the literally canvas API so it can support this kind of thing. This would mean that users can make their drawing app collaborative regardless on what plugin they are using (i.e. not just TogetherJs). 

I understand that you might not want to make TogetherJs a part of the core code, but the API of "literally canvas" should be good enough such that this can be easily done, which at the moment, it's clearly not!

**Comment by irskep** [comment] 2016-03-03 16:40
Dupe of #351

**Closed by irskep** 2016-03-03 16:40 UTC
