### ISSUE TITLE
Zoom in/out centered with the position of mouse?

### ISSUE THREAD

**Issue by yuwenhui** [literallycanvas/literallycanvas#467] opened 2017-07-28 06:26 UTC
When i zoom in/out the canvas, it is centered with the canvas, is there any way to make it centered with the position of mouse? I tried to change the center in setZoom function, but it didn't work.
``` js
setZoom (scale) {
    let center = this.clientCoordsToDrawingCoords(this.targetCanvasElement.width / 2, this.targetCanvasElement.height / 2)
    const oldScale = this.scale
    this.scale = scale
    
    if (this.mousePosition) {
      center = this.mousePosition  // here is the mouse position, i didn't know what's this position should be
    }
    ...
}
```
Can you guys help me? Thanks a lot.

**Comment by irskep** [comment] 2018-01-08 23:21
Please check out 0.5.0. I might have forgotten to release the centering fix I did a while back.

**Comment by irskep** [comment] 2018-01-08 23:27
Duplicate of #456

**Closed by irskep** 2018-01-08 23:27 UTC
Labels: bug
