### ISSUE TITLE
Height of GUI not controllable

### ISSUE THREAD

**Issue by brent-clintel** [literallycanvas/literallycanvas#433] opened 2016-09-28 03:44 UTC
I'm trying to set the size of the literallycanvas GUI to be the full height of the containing div (which I have set to be the height of the the viewport), however, the GUI seems to have a static height.

Setting css properties of `height` or `min-height` on the element passed to `LC.init()` does not effect the height of the GUI.

The height of the literallycanvas GUI is always 400px which seems to be determined by the css `.literally { min-height: '400px';  }.` which is applied to the the `data-reactroot` div.

I see that related tickets, #245, and #389 have all been closed, but I don't believe the issue is actually resolved.  Also there is a similar (but different) open tasks #424, and #393.

How can I get the GUI (the side toolbar and the canvas) to take up the full containing div?

Example:

``` html
<div class="my-drawing" style="min-height:800px; height: 800px;"></div>
<script>
    var canvas = document.getElementsByClassName('my-drawing')[0];
    var lc = LC.init(canvas, {});
</script>
```

In the above example, the GUI that is inserted into the `my-drawing` div is only 400px and not the expected 800px.  I would expect it to take up 800px.

Likewise, if I set height to be `100vh` I would expect the GUI height to take up the full viewport.

**Comment by irskep** [comment] 2016-09-28 03:47
Please post a minimal example of what you've tried.


On Tue, Sep 27, 2016, at 09:44 PM, brent-clintel wrote:
> I'm trying to set the size of the literallycanvas GUI to be the full
> height of the containing div (which I have set to be the height of the
> the viewport), however, the GUI seems to have a static height.
> Setting css properties of height or min-height on the element passed
> to LC.init() does not effect the height of the GUI.
> The height of the literallycanvas GUI is always 400px which seems to
> be determined by the css .literally { min-height: '400px';  }. which
> is applied to the the data-reactroot div.
> I see that related tickets, #245[1], #389[2], #393[3], etc have all
> been closed, but I don't believe the issue is actually resolved.  Also
> there is a similar (but different) open task #424[4].
> How can I get the GUI (the side toolbar and the canvas) to take up the
> full containing div?
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[5], or mute the
> thread[6].
>


Links:

  1. https://github.com/literallycanvas/literallycanvas/issues/245
  2. https://github.com/literallycanvas/literallycanvas/issues/389
  3. https://github.com/literallycanvas/literallycanvas/issues/393
  4. https://github.com/literallycanvas/literallycanvas/issues/424
  5. https://github.com/literallycanvas/literallycanvas/issues/433

**Comment by brent-clintel** [comment] 2016-09-28 03:55
I've edited my post with a minimal example.

**Comment by irskep** [comment] 2016-09-28 05:00
#245 is trivially out of scope for this project. #389 was in fact a docs issue which was resolved and never reopened by its author, but your ticket may indicate a regression. #424 has to do with the shape API. #393 ended up being a bug with how often the canvas is updated when the viewport resizes.

That said, your example looks correct, and I'm not sure what's going on. The API docs say your code should work. Unfortunately I do not have time to debug it.

**Comment by irskep** [comment] 2016-09-28 05:09
I just spent 5 minutes on it. Setting the height like you did worked for me. (I tested by tweaking one of the examples on the documentation site.)

Maybe you could add screenshots of what the page looks like and what the DOM tree looks like in the developer tools?

**Comment by brent-clintel** [comment] 2016-09-28 05:35
This screenshot shows a minimal example of the js and html I used to replicate the issue I have described:
![screenshot from 2016-09-28 15 03 25](https://cloud.githubusercontent.com/assets/4666795/18901730/be99e7e8-858c-11e6-97a3-b56156f134b2.png)

**Comment by brent-clintel** [comment] 2016-09-28 06:00
This is another example, however, this time I have set the size of the '.literally' div with `$('.literally').css('min-height', '100vh');` and added a background image.

![screenshot from 2016-09-28 15 29 32](https://cloud.githubusercontent.com/assets/4666795/18902187/63521140-8590-11e6-9160-7f842d076256.png)

In the screenshot you can see the GUI now takes up the full viewport, however, the background image is of height 400px.

If I try to resize the drawing canvases using javascript `$('.literally canvas').css('min-height', '100vh');` , then the pen gets out of sync with the pixel it draws to on the canvas and the canvases extend below the GUI.

![screenshot from 2016-09-28 15 28 36](https://cloud.githubusercontent.com/assets/4666795/18902170/414065b6-8590-11e6-84a7-170f094f6d73.png)

**Comment by brent-clintel** [comment] 2016-09-29 07:30
I found a bit of a work around to see me through... I added the following to my css on the specific page and the GUI initialised full screen as I expected:

```css
.literally {
  min-height: 100vh;
}
```

I did try previous versions of the JS, but none of them seems to auto size the UI to containing div.

But at least there is a work around.

**Closed** 2017-01-26 19:06 UTC
