### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by idolize** [literallycanvas/literallycanvas#356] opened 2016-01-08 21:25 UTC
I see there is a `package.json`, but I can't find the library on [npm](https://www.npmjs.com/). Any reason for this? It would be great if others could add `literallycanvas` to their package.json.

Let me know if you want help publishing @irskep

**Comment by irskep** [comment] 2016-01-08 21:25
Duplicate of #230, see that ticket for discussion

**Closed by irskep** 2016-01-08 21:25 UTC

**Comment by idolize** [comment] 2016-01-08 21:27
Oops sorry for the duplicate!
