### ISSUE TITLE
unable to draw in v0.4.13 (jQuery based initialization)

### ISSUE THREAD

**Issue by Pakistani** [literallycanvas/literallycanvas#394] opened 2016-04-20 15:29 UTC
Hello,

I am wishing to upgrade my literallycanvas installation to latest verison i.e v0.4.13 but it don't respond at all when i try to draw something and top bar also appears misplaced (unlike it is on demo pages on http://literallycanvas.com/).

I am sure it is something i am doing wrong but i am following the installation instructions and trying to initiatize with following simple code:

<p>&lt;html&gt;<br>
    &lt;head&gt;<br>
    &lt;!-- stylesheet --&gt;<br>
    &lt;link href=&quot;css/literallycanvas.css&quot; rel=&quot;stylesheet&quot;&gt;</p>
<p> &lt;!-- dependency: React.js --&gt;<br>
    &lt;script src=&quot;//cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-with-addons.js&quot;&gt;&lt;/script&gt;<br>
    &lt;script src=&quot;//cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js&quot;&gt;&lt;/script&gt;<br>
    <br>
    &lt;!-- jquery --&gt;<br>
    &lt;script src=&quot;jquery_1.8.3.js&quot;&gt;&lt;/script&gt;<br>
    <br>
    &lt;!-- Literally Canvas --&gt;<br>
    &lt;script src=&quot;js/literallycanvas.js&quot;&gt;&lt;/script&gt;<br>
    &lt;/head&gt;<br>
    &lt;body&gt;<br>
    &lt;div class=&quot;literally&quot;&gt;&lt;/div&gt;<br>
    &lt;script&gt;<br>
    $('.literally').literallycanvas({imageURLPrefix: 'img'})<br>
    &lt;/script&gt;<br>
    &lt;/body&gt;<br>
    &lt;/html&gt;</p>

Any idea if i am doing something wrong or if it is any known bug (i wasn't able to see such reported bug though). Please see the attached image. Many thanks!!

<img width="1283" alt="screen shot 2016-04-20 at 12 00 52" src="https://cloud.githubusercontent.com/assets/1622913/14680314/270cf20a-071d-11e6-9da4-cc4573e31cf2.png">

**Comment by Pakistani** [comment] 2016-04-25 07:53
For others who are in similar situation, this is a real problem with version v0.4.13. I tried above code with version  v0.4.11 and everything works fine.

**Comment by irskep** [comment] 2016-04-25 16:42
It looks to me like a CSS issue. Make sure your style sheet is up to date.

**Comment by Pakistani** [comment] 2016-04-27 08:37
yes, seems so but the css file was up to date. I was using the css file from version v0.4.13

**Comment by vvhh2002** [comment] 2016-05-02 13:00
+1,I use bootstrap + jquery. the css is conflict with these.

**Comment by roarkmccolgan** [comment] 2016-06-01 18:23
+1 I installed via npm and get the exact same issue as mentioned here, I have also tried multiple versions of css (lib/css, css/, scss/) can't get the plugin to work.

Any ideas?
![image](https://cloud.githubusercontent.com/assets/1567162/15720877/a6fc325c-2836-11e6-91a5-84472c74b2f0.png)

**Comment by roarkmccolgan** [comment] 2016-06-01 19:12
I managed to get it working by downloading each file one by one from the literally canvas website and replacing them in my app. Turns out (I think) that the the culprit was literallycanvas.js when using the one attached I got the plugin to work

Oh and I'm only including one react js file "//cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react-with-addons.js"


[literallycanvas.js.zip](https://github.com/literallycanvas/literallycanvas/files/294178/literallycanvas.js.zip)

**Comment by roarkmccolgan** [comment] 2016-06-01 20:56
In summary, what got it to work was using the file I attached in the previous comment and also the using the react file in the same post

**Comment by irskep** [comment] 2016-06-08 18:52
So, I think this is actually a duplicate of #399. Can someone who had this problem try again, but without using the 'literally' class around Literally Canvas?

**Comment by irskep** [comment] 2016-06-08 21:42
Everyone who posted here should probably check out the new installation instructions.

http://literallycanvas.com/installing.html

**Closed by irskep** 2016-06-08 21:43 UTC
Labels: bug
