### ISSUE TITLE
my way to insert a image tools 

### ISSUE THREAD

**Issue by 178620086** [literallycanvas/literallycanvas#302] opened 2015-08-16 06:32 UTC
bad code not to show...
wait my upload a demo

**Comment by 178620086** [comment] 2015-08-16 07:11
oh,no  china GFW is ...

i'm not upload the project..

**Comment by 178620086** [comment] 2015-08-17 02:28
why the new version 0.4.6 has not have Scaling？


。。。。

**Comment by irskep** [comment] 2015-08-17 02:29
Because no one has ever implemented image scaling.

**Comment by 178620086** [comment] 2015-08-17 02:32
you not want to do the first one?

**Comment by irskep** [comment] 2015-08-17 02:33
I'm not going to immediately implement every feature request anyone asks for.

**Comment by 178620086** [comment] 2015-08-17 02:35
will ,ok i wait for you good nows.

**Comment by irskep** [comment] 2015-08-17 02:35
Since this is not a bug report or feature request, I am closing it.

**Closed by irskep** 2015-08-17 02:35 UTC
